pipeline:
  build:
    image: cogniteev/oracle-java
    commands: ./gradlew build shadowJar --no-daemon
  publish:
    image: cogniteev/oracle-java
    commands: ./gradlew publishApiPublicationToParallelBlockRepository --no-daemon
    environment:
      - PUBLISH=yes
    secrets: [SNAPSHOT_REPO, RELEASE_REPO, REPO_USERNAME, REPO_PASSWORD]
    when:
      branch: master
      event: push
